### ISSUE TITLE
加油啊！还会更新吗！真的很希望能够markdown+git写东西，但是转回docx即便有模板对于毕业论文这种也很难无损双向互转

### ISSUE THREAD

**Issue by ywz978020607** [ilcpm/pandoc_markdown2docx_instuction#3]

**Comment by ilcpm** [comment]
总体内容是出来了的，我们自己写的插件是能用的，但是目前期末比较忙，寒假会整理了发布出来
不过还是不建议抱太大希望，有些功能缺陷先说一下

- 一个是页眉页脚的设置极其复杂，虽然我们成功实现了我们学校毕业论文的刁钻要求，但是制作过程比较麻烦痛苦
- 另外公式受限于Word自身公式的限制，并不完善，不过预留了保留LaTeX代码的功能，可以到Word里自行使用其他工具把LaTeX代码转换成第三方公式
- 再有就是参考文献，转录进Word之后，在Word端就不那么好更新了
- 像双栏图片这种Word本身就没有的东西对我们来说就太麻烦了，属于是无限放鸽子的内容

其他部分总体而言完成度挺高，可以随时脱离Markdown流程切换回纯Word的模式而不影响任何功能，我这里把最终的效果展示文档放在后面（不过上次查看的时候又发现了个bug需要处理……）

**另外不要指望能同时转为LaTeX和Word**，我们自己对Markdown增加了很多语法适配，但是这样的语法适配转换到LaTeX……

**所以这个项目可能本身只适用于从Markdown到Word的转换**，其意义在于在格式不太刁钻的情况下结合了LaTeX的优势和纯文本的优势但是又避开了LaTeX的烦人编译和语法冗杂

[template.docx](https://github.com/ilcpm/pandoc_markdown2docx_instuction/files/7808603/template.docx)

**Comment by ywz978020607** [comment]
非常感谢🙏  确实，md-》word困难重重，还是单纯当书写工具再复制粘贴吧，好在公式可以用pandoc直接转成word。
祝烤漆顺利
